using AutoMapper;
using VideoClub.Domain.Entities;

public class CustomerMapper : Profile
{
	public CustomerMapper()
	{
		CreateMap<CustomerDTO, Customer>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Id might be ignored if it's generated by the database
            .ForMember(dest => dest.Rentals, opt => opt.Ignore()); // Assuming Rentals will be handled separately
	}
}